spring:
  datasource:
    url: jdbc:mysql://mysql-springboot.mysql.database.azure.com:3306/sms?useSSL=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: mysqlazure
    password: Azerty123456.
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
logging:
  level:
    org.hibernate.SQL: DEBUG
