spring:
  datasource:
    url: jdbc:mysql://mysql-springboot.mysql.database.azure.com:3306/sms?useSSL=true
    username: mysqlazure
    password: Azerty123456.
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect

